import React,{useEffect,useMemo,useState} from 'react';
import { Baby, Heart, Lock, User } from 'lucide-react';
import { Profile } from './types';
import { StorageService } from './services/storage';
import { NotificationService } from './services/notifications';
import { Sidebar } from './components/Sidebar';
import { ProfileSwitcher } from './components/ProfileSwitcher';
import { Dashboard } from './components/Dashboard';
import { MedicalLog } from './components/MedicalLog';
import { History } from './components/History';
import { AiAssistant } from './components/AiAssistant';
import { FamilySettings } from './components/FamilySettings';
import { InstallApp } from './components/InstallApp';
StorageService.initialize();
const App:React.FC=()=>{const [auth,setAuth]=useState(!!StorageService.getUserData()?.isAuthenticated);const [name,setName]=useState('');const [pin,setPin]=useState('');const [error,setError]=useState('');const [tab,setTab]=useState('dashboard');const [profiles,setProfiles]=useState<Profile[]>(StorageService.getProfiles());const [selectedId,setSelectedId]=useState(StorageService.getSelectedProfileId());
 const profile=useMemo(()=>profiles.find(p=>p.id===selectedId)||profiles[0],[profiles,selectedId]);const refreshProfiles=()=>setProfiles([...StorageService.getProfiles()]);
 useEffect(()=>{const check=()=>NotificationService.checkReminders();check();const timer=setInterval(check,60000);return()=>clearInterval(timer);},[]);
 const select=(id:string)=>{setSelectedId(id);StorageService.setSelectedProfileId(id);};const login=async(e:React.FormEvent)=>{e.preventDefault();if(await StorageService.login(name,pin)){setAuth(true);setError('');}else setError('The family name or PIN is incorrect.');};
 if(!auth)return <main className="min-h-screen bg-gray-50 flex items-center justify-center p-5"><div className="w-full max-w-sm bg-white border rounded-lg p-8 shadow-sm"><div className="w-12 h-12 rounded-lg bg-rose-50 text-rose-600 flex items-center justify-center"><Baby/></div><h1 className="text-3xl font-bold mt-5">Koala Family</h1><p className="text-sm text-gray-500 mt-2">Private health records for Liya, Liyan, Sumaiya, and Wajeethu Ali.</p><form onSubmit={login} className="mt-7 space-y-3"><label className="text-xs font-bold text-gray-500">Family account<div className="relative mt-1"><User size={17} className="absolute left-3 top-3.5 text-gray-400"/><input autoFocus value={name} onChange={e=>setName(e.target.value)} className="w-full pl-10 pr-3 py-3 border bg-gray-50 rounded-lg" placeholder="Enter your name"/></div></label>{StorageService.hasPin()&&<label className="block text-xs font-bold text-gray-500">PIN<input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)} className="mt-1 w-full p-3 border bg-gray-50 rounded-lg" placeholder="4–8 digits"/></label>}{error&&<p className="text-xs text-rose-600">{error}</p>}<button className="w-full bg-gray-900 text-white py-3 rounded-lg font-bold flex justify-center gap-2"><Lock size={17}/>Open tracker</button></form></div></main>;
 if(!profile)return <div className="p-10">No profiles are available.</div>;
 const content=tab==='medical'?<MedicalLog profile={profile}/>:tab==='history'?<History profile={profile}/>:tab==='ai'?<AiAssistant profile={profile}/>:tab==='settings'?<FamilySettings profile={profile} onProfilesChanged={refreshProfiles}/>:<Dashboard profile={profile} onNavigateToRegistry={()=>setTab('medical')}/>;
 return <div className="min-h-screen bg-gray-50"><Sidebar activeTab={tab} setActiveTab={setTab}/><div className="md:ml-64"><header className="sticky top-0 z-40 bg-white/95 backdrop-blur border-b px-4 md:px-6 py-3"><div className="max-w-6xl mx-auto flex flex-col lg:flex-row lg:items-center justify-between gap-2"><div className="flex items-center justify-between gap-3"><div><h1 className="font-bold text-gray-900">{tab==='medical'?'Health log':tab==='ai'?'Health assistant':tab==='settings'?'Family settings':tab[0].toUpperCase()+tab.slice(1)}</h1><p className="text-[11px] text-gray-400 flex gap-1 items-center"><Heart size={11}/>Liya and Liyan family care</p></div><InstallApp/></div><ProfileSwitcher profiles={profiles} selectedId={profile.id} onSelect={select}/></div></header><main className="max-w-6xl mx-auto p-3 md:p-5 pb-20">{content}</main></div></div>;
};
export default App;
