import React,{useEffect,useRef,useState} from 'react';
import { AlertTriangle, Bot, Send } from 'lucide-react';
import { MedicalRecord, Profile } from '../types';
import { StorageService } from '../services/storage';
import { GeminiService } from '../services/gemini';
interface Props{profile:Profile;}
interface Message{role:'user'|'assistant';text:string;}
export const AiAssistant:React.FC<Props>=({profile})=>{const [messages,setMessages]=useState<Message[]>([]);const [input,setInput]=useState('');const [loading,setLoading]=useState(false);const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{setMessages([{role:'assistant',text:`I can help explain general health information for ${profile.name}. I cannot diagnose illness or choose medicine doses.`}]);},[profile.id]);useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages]);
 const send=async(e:React.FormEvent)=>{e.preventDefault();if(!input.trim()||loading)return;const q=input.trim();setInput('');setMessages(m=>[...m,{role:'user',text:q}]);setLoading(true);const records:MedicalRecord[]=await StorageService.getRecords(profile.id);const answer=await GeminiService.ask(q,profile,records);setMessages(m=>[...m,{role:'assistant',text:answer}]);setLoading(false);};
 return <div className="max-w-3xl mx-auto bg-white border rounded-lg overflow-hidden h-[calc(100vh-220px)] min-h-[520px] flex flex-col"><header className="p-5 border-b"><h2 className="font-bold flex gap-2"><Bot size={20}/>Health assistant for {profile.name}</h2><p className="text-xs text-amber-700 mt-2 flex gap-1"><AlertTriangle size={13}/>Do not use this chat for emergencies or medication dosing.</p></header><div className="flex-1 overflow-y-auto p-5 space-y-4 bg-gray-50">{messages.map((m,i)=><div key={i} className={`max-w-[82%] p-4 rounded-lg text-sm leading-relaxed ${m.role==='user'?'ml-auto bg-gray-900 text-white':'bg-white border'}`}>{m.text}</div>)}{loading&&<div className="text-sm text-gray-400">Thinking...</div>}<div ref={end}/></div><form onSubmit={send} className="p-4 border-t flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} placeholder={`Ask about ${profile.name}'s health records`} className="flex-1 p-3 border bg-gray-50 rounded-lg"/><button disabled={!input.trim()||loading} title="Send" className="bg-gray-900 disabled:opacity-40 text-white w-12 rounded-lg flex items-center justify-center"><Send size={18}/></button></form></div>;
};
