import React,{useCallback,useEffect,useMemo,useState} from 'react';
import { Activity,Baby,Cake,Calendar,CalendarHeart,Heart,Hourglass,Lightbulb,Loader2,Moon,PartyPopper,Plus,RefreshCw,Ruler,Scale,Syringe,Thermometer,TimerReset,Utensils } from 'lucide-react';
import { DailyFamilyInsight,MedicalRecord,Profile,ProfileKind,RecordType } from '../types';
import { StorageService } from '../services/storage';
import { GeminiService } from '../services/gemini';
import { formatDate,getAge,getLifeStats,LifeStats,localDateString } from '../services/date';
interface Props{profile:Profile;onNavigateToRegistry:()=>void;}
interface TimeParts{days:number;hours:number;minutes:number;seconds:number;}
const TimeGrid:React.FC<{parts:TimeParts;dark?:boolean}>=({parts,dark=false})=><div className="grid grid-cols-4 gap-1.5 mt-3">{[['DAYS',parts.days.toLocaleString()],['HRS',String(parts.hours).padStart(2,'0')],['MIN',String(parts.minutes).padStart(2,'0')],['SEC',String(parts.seconds).padStart(2,'0')]].map(([label,value])=><div key={label} className={`min-w-0 rounded-md px-1 py-1.5 text-center ${dark?'bg-white/10':'bg-gray-50'}`}><p className="text-base font-bold tabular-nums truncate">{value}</p><p className="text-[8px] font-bold mt-0.5 text-gray-400">{label}</p></div>)}</div>;
const LifeMoments:React.FC<{profile:Profile;life:LifeStats;live:{birthday:TimeParts;elapsed:TimeParts}}>=({profile,life,live})=>{const role=profile.id==='sumaiya'?'Mom':profile.id==='wajeethu-ali'?'Dad':profile.name;return <section><div className="flex items-end justify-between gap-3 mb-3"><div><h3 className="text-lg font-bold text-gray-900">Life moments</h3><p className="text-xs text-gray-400">Live counters for {role}</p></div><span className="text-[10px] font-bold text-gray-400 uppercase">Updates every second</span></div><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3"><article className="bg-gray-900 text-white rounded-lg p-5 min-w-0"><div className="flex items-center justify-between"><div className="w-12 h-12 rounded-lg bg-rose-500 flex items-center justify-center"><PartyPopper size={25}/></div><Cake size={24} className="text-rose-300"/></div><h4 className="font-bold mt-4">Next birthday</h4>{life.daysToBirthday===0?<p className="text-2xl font-bold mt-5 text-rose-300">Birthday today!</p>:<TimeGrid parts={live.birthday} dark/>}<p className="text-xs text-gray-400 mt-3">{formatDate(life.nextBirthday)}</p></article><article className="bg-white border border-gray-200 rounded-lg p-5 min-w-0"><div className="w-12 h-12 rounded-lg bg-sky-100 text-sky-700 flex items-center justify-center"><TimerReset size={25}/></div><h4 className="font-bold mt-4">Time since birth</h4><TimeGrid parts={live.elapsed}/><p className="text-xs text-gray-400 mt-3">Live lifetime clock</p></article><article className="bg-white border border-gray-200 rounded-lg p-5"><div className="w-12 h-12 rounded-lg bg-emerald-100 text-emerald-700 flex items-center justify-center"><CalendarHeart size={25}/></div><p className="text-4xl font-bold mt-5 tabular-nums">{life.totalWeeks.toLocaleString()}</p><h4 className="font-bold mt-2">Completed weeks</h4><p className="text-xs text-gray-400 mt-1">{life.totalDays.toLocaleString()} total days</p></article><article className="bg-white border border-gray-200 rounded-lg p-5"><div className="w-12 h-12 rounded-lg bg-amber-100 text-amber-700 flex items-center justify-center"><Hourglass size={25}/></div><p className="text-3xl font-bold mt-5 tabular-nums">{life.years}y {life.months}m {life.days}d</p><h4 className="font-bold mt-2">Exact age today</h4><p className="text-xs text-gray-400 mt-1">From {formatDate(profile.birthDate!)}</p></article></div></section>;};
export const Dashboard:React.FC<Props>=({profile,onNavigateToRegistry})=>{
 const [records,setRecords]=useState<MedicalRecord[]>([]);const [insight,setInsight]=useState<DailyFamilyInsight|null>(null);const [insightLoading,setInsightLoading]=useState(false);const [now,setNow]=useState(()=>new Date());const today=localDateString(now);
 const load=useCallback(()=>StorageService.getRecords(profile.id).then(setRecords),[profile.id]);
 const loadInsight=useCallback(async(force=false)=>{if(profile.kind!==ProfileKind.CHILD)return;setInsightLoading(true);setInsight(await GeminiService.getDailyFamilyInsight(profile,force));setInsightLoading(false);},[profile,today]);
 useEffect(()=>{load();window.addEventListener('koalaDataChanged',load);return()=>window.removeEventListener('koalaDataChanged',load);},[load]);
 useEffect(()=>{setInsight(null);loadInsight();},[loadInsight]);
 useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(timer);},[]);
 const latest=(type:RecordType)=>records.find(r=>r.type===type);
 const upcoming=records.filter(r=>(r.type===RecordType.APPOINTMENT||r.type===RecordType.VACCINATION)&&r.date>=today).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,2);
 const recent=records.slice(0,3);const counts=useMemo(()=>({feeds:records.filter(r=>r.date===today&&r.type===RecordType.FEEDING).length,sleep:records.filter(r=>r.date===today&&r.type===RecordType.SLEEP).length,diapers:records.filter(r=>r.date===today&&r.type===RecordType.DIAPER).length}),[records,today]);
 const cards=[{label:'Weight',record:latest(RecordType.WEIGHT),icon:Scale,color:'text-emerald-600 bg-emerald-50'},{label:'Height',record:latest(RecordType.HEIGHT),icon:Ruler,color:'text-sky-600 bg-sky-50'},{label:'Temperature',record:latest(RecordType.TEMPERATURE),icon:Thermometer,color:'text-rose-600 bg-rose-50'}];const life=getLifeStats(profile.birthDate,now);
 const live=useMemo(()=>{if(!profile.birthDate||!life)return null;const birth=new Date(`${profile.birthDate}T00:00:00`);const birthday=new Date(`${life.nextBirthday}T00:00:00`);const remaining=Math.max(0,birthday.getTime()-now.getTime());const elapsed=Math.max(0,now.getTime()-birth.getTime());const split=(value:number)=>{const totalSeconds=Math.floor(value/1000);return {days:Math.floor(totalSeconds/86400),hours:Math.floor(totalSeconds%86400/3600),minutes:Math.floor(totalSeconds%3600/60),seconds:totalSeconds%60};};return {birthday:split(remaining),elapsed:split(elapsed)};},[profile.birthDate,life?.nextBirthday,now]);
 return <div className={`grid gap-4 animate-fade-in dashboard-fit ${profile.kind===ProfileKind.CHILD?'dashboard-child':'dashboard-adult'} ${profile.id==='liyan'?'dashboard-liyan':''}`}>
  <section className="bg-white border border-gray-200 p-4 rounded-lg flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="flex items-center gap-3">{profile.photo?<img src={profile.photo} alt={`${profile.name} profile`} className="w-16 h-16 rounded-lg object-cover border border-gray-200"/>:<div className="w-16 h-16 rounded-lg flex items-center justify-center text-white text-2xl font-bold" style={{background:profile.color}}>{profile.name.charAt(0)}</div>}<div><h2 className="text-2xl font-bold text-gray-900">{profile.name}</h2><p className="text-sm text-gray-500 mt-1">{getAge(profile.birthDate)}{profile.birthDate?` • Born ${formatDate(profile.birthDate)}`:''}</p>{profile.allergies&&<p className="mt-1 text-xs font-semibold text-rose-600">Allergies: {profile.allergies}</p>}</div></div><button onClick={onNavigateToRegistry} className="bg-gray-900 text-white px-4 py-2.5 rounded-lg text-sm font-bold flex items-center justify-center gap-2"><Plus size={17}/>Add health entry</button></section>
  {life&&live&&<LifeMoments profile={profile} life={life} live={live}/>}
  {profile.kind===ProfileKind.CHILD&&<section className="bg-white border border-gray-200 rounded-lg overflow-hidden"><div className="px-6 py-4 border-b flex items-center justify-between"><div><h3 className="font-bold">இன்றைய குறிப்பு - {profile.name}</h3><p className="text-xs text-gray-400 mt-1">அன்பான தினசரிச் செய்தியும் வயதிற்கு ஏற்ற பொதுவான வழிகாட்டலும்</p></div><button onClick={()=>loadInsight(true)} disabled={insightLoading} title="புதிய தினசரிக் குறிப்பை உருவாக்கவும்" className="p-2 text-gray-400 hover:text-gray-900 disabled:opacity-40">{insightLoading?<Loader2 size={18} className="animate-spin"/>:<RefreshCw size={18}/>}</button></div>{insight?<div className="grid md:grid-cols-2"><div className="p-6 md:border-r border-gray-200"><div className="flex items-center gap-2 text-rose-600"><Heart size={18}/><h4 className="text-xs font-bold">{profile.name} அம்மாவிடம் சொல்வது</h4></div><p className="mt-4 text-lg font-semibold leading-relaxed text-gray-800">“{insight.babyMessage}”</p></div><div className="p-6 bg-amber-50/50"><div className="flex items-center gap-2 text-amber-700"><Lightbulb size={18}/><h4 className="text-xs font-bold">அம்மாவுக்கான ஆலோசனை</h4></div><p className="mt-4 text-sm leading-relaxed text-gray-700">{insight.momAdvice}</p><p className="text-[10px] text-gray-400 mt-4">பொதுவான வழிகாட்டல் மட்டும் {insight.source==='fallback'?'• இணையமில்லா குறிப்பு':'• AI உருவாக்கியது'}</p></div></div>:<div className="p-8 flex items-center justify-center gap-2 text-sm text-gray-400"><Loader2 size={18} className="animate-spin"/>இன்றைய குறிப்பைத் தயாரிக்கிறது...</div>}</section>}
  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{cards.map(({label,record,icon:Icon,color})=><div key={label} className="bg-white border border-gray-200 rounded-lg p-5"><div className={`w-10 h-10 rounded-lg flex items-center justify-center ${color}`}><Icon size={20}/></div><p className="text-xs font-bold uppercase text-gray-400 mt-4">Latest {label}</p><p className="text-2xl font-bold mt-1">{record?.value!==undefined?`${record.value} ${record.unit||''}`:'Not recorded'}</p>{record&&<p className="text-xs text-gray-400 mt-1">{formatDate(record.date)}</p>}</div>)}</div>
  {profile.id==='liyan'&&<section><h3 className="text-lg font-bold mb-3">Today for Liyan</h3><div className="grid grid-cols-3 gap-3">{[[Utensils,'Feeds',counts.feeds],[Moon,'Sleep logs',counts.sleep],[Baby,'Diapers',counts.diapers]].map(([Icon,label,value]:any)=><div key={label} className="bg-white border rounded-lg p-4 text-center"><Icon className="mx-auto text-sky-600" size={20}/><p className="text-2xl font-bold mt-2">{value}</p><p className="text-xs text-gray-400">{label}</p></div>)}</div></section>}
  <div className="grid lg:grid-cols-2 gap-6"><section className="bg-white border rounded-lg p-6"><h3 className="font-bold flex items-center gap-2"><Calendar size={18}/>Upcoming care</h3><div className="mt-4 space-y-3">{upcoming.length?upcoming.map(r=><div key={r.id} className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg"><Syringe size={17} className="text-rose-500"/><div><p className="font-semibold text-sm">{r.title}</p><p className="text-xs text-gray-400">{formatDate(r.date)}{r.location?` • ${r.location}`:''}</p></div></div>):<p className="text-sm text-gray-400 py-5">No upcoming appointments or vaccines.</p>}</div></section><section className="bg-white border rounded-lg p-6"><h3 className="font-bold flex items-center gap-2"><Activity size={18}/>Recent activity</h3><div className="mt-4 divide-y">{recent.length?recent.map(r=><div key={r.id} className="py-3 flex justify-between gap-3"><div><p className="font-semibold text-sm">{r.title}</p><p className="text-xs text-gray-400">{r.type}</p></div><span className="text-xs text-gray-400 whitespace-nowrap">{formatDate(r.date)}</span></div>):<p className="text-sm text-gray-400 py-5">No records yet.</p>}</div></section></div>
  <p className="text-xs text-gray-400 flex gap-2"><Baby size={14}/>This tracker supports record keeping and does not replace advice from your child’s clinician.</p>
 </div>;
};
