import React,{useEffect,useRef,useState} from 'react';
import { Camera, Download, Save, Upload, Plus, Trash2, X } from 'lucide-react';
import { BackupData, Medicine, Profile } from '../types';
import { StorageService } from '../services/storage';
import { localDateString } from '../services/date';
interface Props{profile:Profile;onProfilesChanged:()=>void;}
export const FamilySettings:React.FC<Props>=({profile,onProfilesChanged})=>{const [draft,setDraft]=useState(profile);const [pin,setPin]=useState('');const [meds,setMeds]=useState<Medicine[]>([]);const [med,setMed]=useState({name:'',dosage:'',reason:'',prescribingDoctor:'',startDate:localDateString(),endDate:'',reminderTimes:''});const backupFile=useRef<HTMLInputElement>(null);const photoFile=useRef<HTMLInputElement>(null);
 useEffect(()=>{setDraft(profile);StorageService.getMedicines(profile.id).then(setMeds);},[profile]);
 const saveProfile=()=>{StorageService.saveProfile(draft);onProfilesChanged();alert('Profile saved.');};
 const addMedicine=async(e:React.FormEvent)=>{e.preventDefault();if(!med.name.trim())return;await StorageService.saveMedicine({id:StorageService.generateId(),profileId:profile.id,...med,reminderTimes:med.reminderTimes.split(',').map(x=>x.trim()).filter(Boolean)});setMed({...med,name:'',dosage:'',reason:'',prescribingDoctor:'',endDate:'',reminderTimes:''});setMeds(await StorageService.getMedicines(profile.id));};
 const download=()=>{const blob=new Blob([JSON.stringify(StorageService.exportData(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`koala-family-backup-${localDateString()}.json`;a.click();URL.revokeObjectURL(a.href);};
 const restore=async(e:React.ChangeEvent<HTMLInputElement>)=>{const chosen=e.target.files?.[0];if(!chosen)return;try{const data=JSON.parse(await chosen.text()) as BackupData;if(confirm('Replace current family records with this backup?')){StorageService.importData(data);onProfilesChanged();alert('Backup restored.');}}catch(err:any){alert(err.message||'Could not read backup.');}e.target.value='';};
 const choosePhoto=(e:React.ChangeEvent<HTMLInputElement>)=>{const chosen=e.target.files?.[0];if(!chosen)return;if(!chosen.type.startsWith('image/')){alert('Please choose an image file.');return;}const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const size=512,scale=Math.min(1,size/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height);setDraft(current=>({...current,photo:canvas.toDataURL('image/jpeg',0.82)}));};image.src=String(reader.result);};reader.readAsDataURL(chosen);e.target.value='';};
 return <div className="grid lg:grid-cols-2 gap-6 animate-fade-in"><div className="space-y-6"><section className="bg-white border rounded-lg p-6 space-y-4"><h2 className="text-xl font-bold">{profile.name}'s profile</h2><div className="flex items-center gap-4">{draft.photo?<img src={draft.photo} alt={`${draft.name} profile preview`} className="w-24 h-24 rounded-lg object-cover border"/>:<div className="w-24 h-24 rounded-lg flex items-center justify-center text-white text-3xl font-bold" style={{background:draft.color}}>{draft.name.charAt(0)}</div>}<div className="space-y-2"><button type="button" onClick={()=>photoFile.current?.click()} className="border px-4 py-2 rounded-lg font-bold text-sm flex gap-2"><Camera size={17}/>{draft.photo?'Change photo':'Add photo'}</button>{draft.photo&&<button type="button" onClick={()=>setDraft({...draft,photo:undefined})} className="text-rose-600 px-3 py-1 text-xs font-bold flex gap-1"><X size={15}/>Remove photo</button>}<input ref={photoFile} type="file" accept="image/jpeg,image/png,image/webp" onChange={choosePhoto} className="hidden"/><p className="text-[10px] text-gray-400">Photo is resized and stored on this device.</p></div></div>{profile.birthDate&&<label className="block text-xs font-bold text-gray-500">Birth date<input type="date" max={localDateString()} value={draft.birthDate||''} onChange={e=>setDraft({...draft,birthDate:e.target.value})} className="mt-1 w-full p-3 border bg-gray-50 rounded-lg"/></label>}<label className="block text-xs font-bold text-gray-500">Known allergies<input value={draft.allergies} onChange={e=>setDraft({...draft,allergies:e.target.value})} placeholder="Write none if confirmed" className="mt-1 w-full p-3 border bg-gray-50 rounded-lg"/></label><label className="block text-xs font-bold text-gray-500">Important notes<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} rows={3} className="mt-1 w-full p-3 border bg-gray-50 rounded-lg"/></label><button onClick={saveProfile} className="bg-gray-900 text-white px-4 py-3 rounded-lg font-bold flex gap-2"><Save size={18}/>Save profile</button></section>
 <section className="bg-white border rounded-lg p-6"><h2 className="text-xl font-bold">Privacy and backup</h2><p className="text-sm text-gray-500 mt-2">Set a device PIN, and download backups regularly because records live in this browser.</p><div className="flex gap-2 mt-4"><input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)} placeholder="New 4–8 digit PIN" className="min-w-0 flex-1 p-3 border bg-gray-50 rounded-lg"/><button onClick={async()=>{try{await StorageService.setPin(pin);setPin('');alert('PIN saved. Use it the next time you sign in.');}catch(e:any){alert(e.message);}}} className="border px-4 rounded-lg font-bold text-sm">Set PIN</button></div><div className="flex flex-wrap gap-2 mt-4"><button onClick={download} className="border px-4 py-3 rounded-lg font-bold text-sm flex gap-2"><Download size={17}/>Download backup</button><button onClick={()=>backupFile.current?.click()} className="border px-4 py-3 rounded-lg font-bold text-sm flex gap-2"><Upload size={17}/>Restore</button><button onClick={StorageService.logout} className="border px-4 py-3 rounded-lg font-bold text-sm">Lock app</button><input ref={backupFile} type="file" accept="application/json" onChange={restore} className="hidden"/></div></section></div>
 <section className="bg-white border rounded-lg p-6 h-fit"><h2 className="text-xl font-bold">{profile.name}'s medicines</h2><form onSubmit={addMedicine} className="mt-4 grid grid-cols-2 gap-3"><input required value={med.name} onChange={e=>setMed({...med,name:e.target.value})} placeholder="Medicine name" className="col-span-2 p-3 border bg-gray-50 rounded-lg"/><input value={med.dosage} onChange={e=>setMed({...med,dosage:e.target.value})} placeholder="Dose, e.g. 2.5 ml" className="p-3 border bg-gray-50 rounded-lg"/><input value={med.reminderTimes} onChange={e=>setMed({...med,reminderTimes:e.target.value})} placeholder="Times: 08:00, 20:00" className="p-3 border bg-gray-50 rounded-lg"/><input value={med.reason} onChange={e=>setMed({...med,reason:e.target.value})} placeholder="Reason" className="p-3 border bg-gray-50 rounded-lg"/><input value={med.prescribingDoctor} onChange={e=>setMed({...med,prescribingDoctor:e.target.value})} placeholder="Prescribing doctor" className="p-3 border bg-gray-50 rounded-lg"/><button className="col-span-2 bg-gray-900 text-white p-3 rounded-lg font-bold flex justify-center gap-2"><Plus size={18}/>Add medicine</button></form><div className="mt-6 divide-y">{meds.map(m=><div key={m.id} className="py-4 flex justify-between"><div><p className="font-bold">{m.name} <span className="text-sm text-gray-400">{m.dosage}</span></p><p className="text-xs text-gray-500">{m.reason}{m.reminderTimes.length?` • ${m.reminderTimes.join(', ')}`:''}</p></div><button onClick={async()=>{if(confirm('Remove this medicine?')){await StorageService.deleteMedicine(m.id);setMeds(await StorageService.getMedicines(profile.id));}}} title="Remove"><Trash2 size={17} className="text-gray-400"/></button></div>)}</div></section></div>;
};
