import React,{useCallback,useEffect,useMemo,useState} from 'react';
import { Download, Printer, TrendingUp } from 'lucide-react';
import { MedicalRecord, Profile, RecordType } from '../types';
import { StorageService } from '../services/storage';
import { formatDate } from '../services/date';
interface Props{profile:Profile;}
const esc=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;
export const History:React.FC<Props>=({profile})=>{const [records,setRecords]=useState<MedicalRecord[]>([]);const load=useCallback(()=>StorageService.getRecords(profile.id).then(setRecords),[profile.id]);useEffect(()=>{load();},[load]);
 const growth=useMemo(()=>records.filter(r=>[RecordType.WEIGHT,RecordType.HEIGHT,RecordType.HEAD_CIRCUMFERENCE].includes(r.type)&&r.value!==undefined).sort((a,b)=>a.date.localeCompare(b.date)),[records]);
 const vaccines=records.filter(r=>r.type===RecordType.VACCINATION);const max=Math.max(1,...growth.map(r=>r.value||0));
 const csv=()=>{const rows=[['Profile','Date','Time','Type','Title','Value','Unit','Status','Location','Notes'],...records.map(r=>[profile.name,r.date,r.time,r.type,r.title,r.value,r.unit,r.status,r.location,r.details])];const blob=new Blob([rows.map(row=>row.map(esc).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${profile.name.toLowerCase()}-health-history.csv`;a.click();URL.revokeObjectURL(a.href);};
 return <div className="space-y-6 animate-fade-in"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">{profile.name}'s history</h2><p className="text-sm text-gray-400">{records.length} health entries</p></div><div className="flex gap-2"><button onClick={csv} className="border bg-white px-4 py-2 rounded-lg text-sm font-bold flex gap-2"><Download size={17}/>CSV</button><button onClick={()=>window.print()} className="border bg-white px-4 py-2 rounded-lg text-sm font-bold flex gap-2"><Printer size={17}/>Print</button></div></div>
 <section className="bg-white border rounded-lg p-6"><h3 className="font-bold flex gap-2"><TrendingUp size={18}/>Growth measurements</h3>{growth.length?<div className="mt-5 space-y-3">{growth.map(r=><div key={r.id} className="grid grid-cols-[90px_1fr_75px] gap-3 items-center text-xs"><span className="text-gray-400">{formatDate(r.date)}</span><div className="h-7 bg-gray-100 rounded overflow-hidden"><div className={`h-full ${r.type===RecordType.WEIGHT?'bg-emerald-400':r.type===RecordType.HEIGHT?'bg-sky-400':'bg-amber-400'} flex items-center px-2 text-white font-bold whitespace-nowrap`} style={{width:`${Math.max(12,(r.value||0)/max*100)}%`}}>{r.type}</div></div><strong className="text-right">{r.value} {r.unit}</strong></div>)}</div>:<p className="text-sm text-gray-400 mt-4">Add weight, height, or head circumference to begin the chart.</p>}</section>
 <section className="bg-white border rounded-lg p-6"><h3 className="font-bold">Vaccination record</h3><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-xs text-gray-400 border-b"><tr><th className="py-3">Vaccine</th><th>Date</th><th>Dose</th><th>Next due</th><th>Status</th></tr></thead><tbody>{vaccines.map(r=><tr key={r.id} className="border-b last:border-0"><td className="py-3 font-semibold">{r.title}</td><td>{formatDate(r.date)}</td><td>{r.doseNumber||'—'}</td><td>{r.nextDueDate?formatDate(r.nextDueDate):'—'}</td><td>{r.status||'—'}</td></tr>)}</tbody></table>{!vaccines.length&&<p className="text-sm text-gray-400 py-5">No vaccinations recorded.</p>}</div></section>
 <section className="bg-white border rounded-lg p-6"><h3 className="font-bold">Complete timeline</h3><div className="mt-3 divide-y">{records.map(r=><div key={r.id} className="py-4 flex justify-between gap-5"><div><p className="font-semibold">{r.title}</p><p className="text-sm text-gray-500 mt-1">{r.type}{r.details?` • ${r.details}`:''}</p></div><span className="text-xs text-gray-400 whitespace-nowrap">{formatDate(r.date)}</span></div>)}</div></section></div>;
};
