import React,{useCallback,useEffect,useMemo,useState} from 'react';
import { Check, Edit3, Plus, Trash2, X } from 'lucide-react';
import { EventStatus, MedicalRecord, Profile, RecordType } from '../types';
import { StorageService } from '../services/storage';
import { formatDate, localDateString } from '../services/date';
interface Props{profile:Profile;}
const measurement:Partial<Record<RecordType,string>>={[RecordType.WEIGHT]:'kg',[RecordType.HEIGHT]:'cm',[RecordType.HEAD_CIRCUMFERENCE]:'cm',[RecordType.TEMPERATURE]:'°C',[RecordType.SLEEP]:'hours',[RecordType.FEEDING]:'ml'};
const types=[RecordType.NOTE,RecordType.SYMPTOM,RecordType.TEMPERATURE,RecordType.WEIGHT,RecordType.HEIGHT,RecordType.HEAD_CIRCUMFERENCE,RecordType.VACCINATION,RecordType.APPOINTMENT,RecordType.MEDICINE,RecordType.FEEDING,RecordType.SLEEP,RecordType.DIAPER,RecordType.DENTAL];
export const MedicalLog:React.FC<Props>=({profile})=>{
 const empty=()=>({type:RecordType.NOTE,title:'',details:'',date:localDateString(),time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false}),value:'',unit:'',location:'',status:EventStatus.COMPLETED,doseNumber:'',nextDueDate:''});
 const [form,setForm]=useState(empty);const [editing,setEditing]=useState<string|null>(null);const [records,setRecords]=useState<MedicalRecord[]>([]);const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');
 const load=useCallback(()=>StorageService.getRecords(profile.id).then(setRecords),[profile.id]);useEffect(()=>{load();setForm(empty());setEditing(null);},[load]);
 const set=(key:string,value:any)=>setForm(prev=>({...prev,[key]:value}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const numeric=form.value===''?undefined:Number(form.value);if(numeric!==undefined&&(!Number.isFinite(numeric)||numeric<0))return alert('Enter a valid non-negative measurement.');
  const data={profileId:profile.id,type:form.type,title:form.title.trim()||form.type,details:form.details.trim(),date:form.date,time:form.time,value:numeric,unit:form.unit||measurement[form.type],location:form.location.trim(),status:form.status,doseNumber:form.doseNumber.trim(),nextDueDate:form.nextDueDate||undefined};
  if(editing)await StorageService.updateRecord({...data,id:editing} as MedicalRecord);else await StorageService.addRecord(data);setForm(empty());setEditing(null);load();};
 const edit=(r:MedicalRecord)=>{setEditing(r.id);setForm({type:r.type,title:r.title,details:r.details||'',date:r.date,time:r.time||'',value:r.value?.toString()||'',unit:r.unit||'',location:r.location||'',status:r.status||EventStatus.COMPLETED,doseNumber:r.doseNumber||'',nextDueDate:r.nextDueDate||''});window.scrollTo({top:0,behavior:'smooth'});};
 const remove=async(id:string)=>{if(confirm('Delete this health entry?')){await StorageService.deleteRecord(id);load();}};
 const visible=useMemo(()=>records.filter(r=>(filter==='all'||r.type===filter)&&(`${r.title} ${r.details}`.toLowerCase().includes(query.toLowerCase()))),[records,filter,query]);const hasValue=measurement[form.type];
 return <div className="grid xl:grid-cols-[420px_1fr] gap-7 animate-fade-in"><form onSubmit={submit} className="bg-white border rounded-lg p-6 space-y-4 h-fit xl:sticky xl:top-28"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing?'Edit entry':'New health entry'}</h2>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty());}} title="Cancel"><X/></button>}</div>
  <label className="block text-xs font-bold text-gray-500">Record type<select value={form.type} onChange={e=>{const t=e.target.value as RecordType;setForm(prev=>({...prev,type:t,unit:measurement[t]||''}));}} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg">{types.map(t=><option key={t}>{t}</option>)}</select></label>
  <div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold text-gray-500">Date<input required type="date" max={form.type===RecordType.APPOINTMENT||form.type===RecordType.VACCINATION?undefined:localDateString()} value={form.date} onChange={e=>set('date',e.target.value)} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg"/></label><label className="text-xs font-bold text-gray-500">Time<input type="time" value={form.time} onChange={e=>set('time',e.target.value)} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg"/></label></div>
  <label className="block text-xs font-bold text-gray-500">Title<input required value={form.title} onChange={e=>set('title',e.target.value)} placeholder={form.type==='Vaccine'?'e.g. MMR dose 1':`Describe the ${form.type.toLowerCase()}`} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg"/></label>
  {hasValue&&<div className="grid grid-cols-[1fr_100px] gap-3"><label className="text-xs font-bold text-gray-500">Measurement<input required type="number" min="0" step="0.01" value={form.value} onChange={e=>set('value',e.target.value)} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg"/></label><label className="text-xs font-bold text-gray-500">Unit<input value={form.unit||hasValue} onChange={e=>set('unit',e.target.value)} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg"/></label></div>}
  {(form.type===RecordType.APPOINTMENT||form.type===RecordType.VACCINATION||form.type===RecordType.DENTAL)&&<label className="block text-xs font-bold text-gray-500">Clinic or location<input value={form.location} onChange={e=>set('location',e.target.value)} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg"/></label>}
  {form.type===RecordType.VACCINATION&&<div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold text-gray-500">Dose number<input value={form.doseNumber} onChange={e=>set('doseNumber',e.target.value)} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg"/></label><label className="text-xs font-bold text-gray-500">Next due<input type="date" min={form.date} value={form.nextDueDate} onChange={e=>set('nextDueDate',e.target.value)} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg"/></label></div>}
  {(form.type===RecordType.APPOINTMENT||form.type===RecordType.VACCINATION)&&<label className="block text-xs font-bold text-gray-500">Status<select value={form.status} onChange={e=>set('status',e.target.value)} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg">{Object.values(EventStatus).map(s=><option key={s}>{s}</option>)}</select></label>}
  <label className="block text-xs font-bold text-gray-500">Notes<textarea rows={3} value={form.details} onChange={e=>set('details',e.target.value)} className="mt-1 w-full p-3 bg-gray-50 border rounded-lg resize-none" placeholder="Symptoms, dosage, findings, or observations"/></label>
  <button className="w-full bg-gray-900 text-white p-3 rounded-lg font-bold flex justify-center gap-2">{editing?<Check size={18}/>:<Plus size={18}/>} {editing?'Save changes':'Add entry'}</button></form>
 <section><div className="flex flex-col sm:flex-row gap-3 mb-5"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${profile.name}'s records`} className="flex-1 p-3 bg-white border rounded-lg"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="p-3 bg-white border rounded-lg"><option value="all">All types</option>{types.map(t=><option key={t}>{t}</option>)}</select></div>
  <div className="space-y-3">{visible.map(r=><article key={r.id} className="bg-white border rounded-lg p-5"><div className="flex justify-between gap-4"><div><div className="flex gap-2 items-center"><span className="text-[10px] uppercase font-bold text-gray-500 bg-gray-100 px-2 py-1 rounded">{r.type}</span>{r.status&&<span className="text-[10px] font-bold text-emerald-600">{r.status}</span>}</div><h3 className="font-bold mt-2">{r.title}</h3><p className="text-xs text-gray-400 mt-1">{formatDate(r.date)} {r.time}{r.location?` • ${r.location}`:''}</p></div><div className="flex gap-1"><button onClick={()=>edit(r)} title="Edit" className="p-2 text-gray-400 hover:text-sky-600"><Edit3 size={17}/></button><button onClick={()=>remove(r.id)} title="Delete" className="p-2 text-gray-400 hover:text-rose-600"><Trash2 size={17}/></button></div></div>{r.value!==undefined&&<p className="mt-3 text-2xl font-bold">{r.value} <span className="text-sm text-gray-400">{r.unit}</span></p>}{r.details&&<p className="mt-3 text-sm text-gray-600 bg-gray-50 p-3 rounded-lg">{r.details}</p>}{r.nextDueDate&&<p className="mt-2 text-xs font-semibold text-rose-600">Next dose due {formatDate(r.nextDueDate)}</p>}</article>)}{!visible.length&&<div className="bg-white border border-dashed rounded-lg p-12 text-center text-gray-400">No matching records for {profile.name}.</div>}</div>
 </section></div>;
};
